### ISSUE TITLE
Build docker image with ENV from Kube

### ISSUE THREAD

**Issue by duyleekun** [hasura/gitkube#105]
There's a shared ENV between build and running phase. Currently, I have to duplicate the ENV from kube manifest into Dockerfile. Is there any way to do that properly yet?

**Comment by duyleekun** [comment]
Does current Remote object support ref to ConfigMap/Secret because I can't find it in the documents. Having ConfigMap/Secret ref-able from `Remote` would solve my use case.

**Comment by tirumaraiselvan** [comment]
That's a great suggestion. Can you please open an issue for the same?
