### ISSUE TITLE
List out supported kubernetes vendors or provide instructions for different kubernetes vendors

### ISSUE THREAD

**Issue by coco98** [hasura/gitkube#26]
Mention specifically what kubernetes distros this works with. I've received lots of questions about whether it works on GKE or not.

**Comment by tirumaraiselvan** [comment]
Gitkube will work with most distros as is because of no external dependency. We have mentioned this in the README now. 

Refer to https://github.com/hasura/gitkube/issues/33 for tracking any non-standard setup requirements.
