### ISSUE TITLE
Cannot generate multiple gitkube remotes on a given cluster using gitkube cli.

### ISSUE THREAD

**Issue by naseemkullah** [hasura/gitkube#83]
Because it errors out on creating an already existing docker-registry secret.

`FATA[0036] generating remote failed: error creating docker-registry secret: secrets "regsecret" already exists`

**Comment by tirumaraiselvan** [comment]
@shahidhk can we name the regsecret as {remote-name}-regsecret to avoid collision? 

@naseemkullah For the time being, you can ignore creating the docker secret through the cli (choose the third option), and then create a docker secret manually  ( https://github.com/hasura/gitkube/blob/master/docs/registry.md) and add it to your remote.yaml
