### ISSUE TITLE
Upgrade client-go

### ISSUE THREAD

**Issue by tirumaraiselvan** [hasura/gitkube#85]
This will support `credentials plugin` (useful for EKS authentication):

https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

**Comment by luigi-riefolo** [comment]
any update on this?

**Comment by tirumaraiselvan** [comment]
Thanks for bumping this. I plan to fix it this week.

**Comment by tirumaraiselvan** [comment]
@prateekpandey14 Super cool! I have been super busy and this is a high priority issue. Thanks for taking it up!

**Comment by prateekpandey14** [comment]
I can see gikube uses `glide`. As all the go tooling uses `dep` for dependency management should we use `dep` instead of `glide` ?

**Comment by tirumaraiselvan** [comment]
@prateekpandey14 Feel free to use dep.
