### ISSUE TITLE
Multi-stage builds ?

### ISSUE THREAD

**Issue by aaparmeggiani** [hasura/gitkube#92]
Hi there, are multi-stage builds supported/planned? (or am I  missing something??)
```
remote: Sending build context to Docker daemon 122.9 kB
remote: Step 1/17 : FROM elixir:1.7-alpine AS builder
remote: Error parsing reference: "elixir:1.7-alpine AS builder" is not a valid repository/tag: invalid reference format
```
--
```
% gitkube version
v0.2.1
```
Thanks in advance,
Andre

**Comment by aaparmeggiani** [comment]
Hmm .. needs docker >= 17.05

> Multi-stage builds are a new feature requiring Docker 17.05 or higher on the daemon and client.

**Comment by tirumaraiselvan** [comment]
I guess we need to update https://github.com/hasura/gitkube/blob/master/build/gitkubed/Dockerfile . Any takers?

**Comment by SeanPrashad** [comment]
Hey @tirumaraiselvan! I'd like to give this a shot. Would we need to update:

https://github.com/hasura/gitkube/blob/23fc06b7f17f4370c5b4e74ee324b7c17a03c5be/build/gitkubed/Dockerfile#L7

to be ` && curl -o /tmp/docker-1.12 'https://get.docker.com/builds/Linux/x86_64/docker-1.17.05.tgz' \ `

and the associated lines that reference `/tmp/docker-1.12`?

**Comment by tirumaraiselvan** [comment]
@SeanPrashad yes, that should be enough.
